### ISSUE TITLE
Adapter registration name includes generic type parameter

### ISSUE THREAD

**Issue by tomaspalaoro** [IO-Design-Team/hive_ce#120]
Hello! First of all, thank you for the fantastic work maintaining this package.
I’ve encountered a small issue and was wondering if there’s a workaround.

Using @GenerateAdapters on a generic class works well, it produces the correct YAML entries and generates the adapter class itself. However, the call to registerAdapter() in the generated file mistakenly appends the type argument to the adapter name, causing a compilation error.

Example
```
class ExampleClass<T extends Base> { 
  // fields and methods
}
```
```
@GenerateAdapters([AdapterSpec<ExampleClass>()])
void main() {}
```
_hive_adapters.g.yaml:_
```
ExampleClass<Base>:
  typeId: 42
  fields:
    field1:
      index: 0
    field2:
      index: 1
```
_hive_registrar.dart:_
```
// Incorrect:
registerAdapter(ExampleClassBaseAdapter());
```
There is no **ExampleClassBaseAdapter** class; the correct adapter name would be **ExampleClassAdapter**.
Is there currently a way to override the adapter’s registration name without going back to the old way of explicitly defining HiveTypes?

- Flutter: 3.24.5
- hive_ce: 2.8.0+3

**Comment by Rexios80** [comment]
> ExampleClass<Base>
> registerAdapter(ExampleClassBaseAdapter());

These both look incorrectly generated. Although I'm not sure adapter generation ever supported generics? What does your real generic class look like? And its generated adapter?

**Comment by tomaspalaoro** [comment]
@Rexios80  Thanks for taking a look, here’s a minimal reproduction that hopefully makes the issue clearer:

```
class Document {
  final String id;

  final String title;

  final String content;

  Document({
    required this.id,
    required this.title,
    required this.content,
  });
}

class InvoiceDocument extends Document {
  final String invoiceNumber;

  final double amount;

  InvoiceDocument({
    required super.id,
    required super.title,
    required super.content,
    required this.invoiceNumber,
    required this.amount,
  });
}

// A generic Line that can wrap any Document subtype.
// We use this so we don’t have to write separate classes for
// Line<Document>, Line<InvoiceDocument>, etc.
class Line<T extends Document> {
  final T document;

  final int lineNumber;

  final DateTime timestamp;

  Line({
    required this.document,
    required this.lineNumber,
    required this.timestamp,
  });
}
```
hive_adapters.dart
```
part 'hive_adapters.g.dart';

@GenerateAdapters([
  AdapterSpec<Document>(),
  AdapterSpec<InvoiceDocument>(),
  AdapterSpec<Line>(),
], firstTypeId: 1)
void _() {}
```

hive_adapters.g.yaml
```
nextTypeId: 4
types:
  Document:
    typeId: 1
    nextIndex: 3
    fields:
      id:
        index: 0
      title:
        index: 1
      content:
        index: 2
  InvoiceDocument:
    typeId: 2
    nextIndex: 5
    fields:
      invoiceNumber:
        index: 0
      amount:
        index: 1
      id:
        index: 2
      title:
        index: 3
      content:
        index: 4
  Line<Document>:
    typeId: 3
    nextIndex: 3
    fields:
      document:
        index: 0
      lineNumber:
        index: 1
      timestamp:
        index: 2

```

hive_registrar.g.dart
```
extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(DocumentAdapter());
    registerAdapter(InvoiceDocumentAdapter());
    registerAdapter(LineDocumentAdapter());
  }
}
```

_The method 'LineDocumentAdapter' isn't defined for the type 'HiveInterface'_

The problem is purely in how the adapter name is constructed. I don’t actually need the generator to understand or support generics at runtime, I just need it to strip off the "Document" when it builds the class name
