### ISSUE TITLE
Choose where to create the hive_registrar.g.dart file

### ISSUE THREAD

**Issue by kaciula** [IO-Design-Team/hive_ce#36]
Is there a way to specify where to create the hive_registrar.g.dart file? Currently, it is being created in the main lib folder. I would much prefer to control where to place it in the file hierarchy (e.g closer to where the database is)

**Comment by Rexios80** [comment]
There is not currently, but I am working on a new way to generate type adapters in https://github.com/IO-Design-Team/hive_ce/pull/35. I will make it so that `hive_registrar.g.dart` is placed in the same directory as the file containing the `@GenerateAdapters` annotation.

**Comment by Rexios80** [comment]
I added the feature to that PR. Could you try this and see if it does what you need?

pubspec.yaml
```yaml
dependency_overrides:
  hive_ce:
    git:
      url: https://github.com/IO-Design-Team/hive_ce
      ref: 7a0792d407d7563f56a88bcb3d8427e4a9315968
      path: hive
  hive_ce_generator:
    git:
      url: https://github.com/IO-Design-Team/hive_ce
      ref: 7a0792d407d7563f56a88bcb3d8427e4a9315968
      path: hive_generator
```

Create a file where you want `hive_registrar.g.dart` to be containing the following:
```dart
import 'package:hive_ce/hive.dart';

part '{YOUR_FILE_NAME}.g.dart';

@GenerateAdapters([])
void _() {}
```

You could transition your project to using `@GenerateAdapters`, but I'm not sure how much work that would be for you (and also the feature is not quite stable yet). If you are interested in attempting the migration for science, see the documentation [here](https://github.com/IO-Design-Team/hive_ce/blob/feature/generate-adapters/hive/README.md#migrating-to-generateadapters).
