### ISSUE TITLE
Dependency issue

### ISSUE THREAD

**Issue by delfme** [IO-Design-Team/hive_ce#62]
**Steps to Reproduce**
Hello,
I added the dependencies:
```
dependencies:
  #hive: ^2.2.3
  #hive_flutter: ^1.1.0
  hive_ce: ^2.8.0+3
  hive_ce_flutter: ^2.8.0+3

dev_dependencies:
  #hive_generator: ^2.0.0
  hive_ce_generator: ^2.8.0+3
```

I’m encountering the following error: 'Because [Name] depends on hive_ce_generator ^2.8.0+3, which doesn’t match any available versions, version solving failed.'

Do you know how I can resolve this issue?

**Version**
 - Platform: iOS, Android
 - Flutter version:  3.24.5,
 - Hive version: 2.8.0+3
