### ISSUE TITLE
Isolate support

### ISSUE THREAD

**Issue by Rexios80** [IO-Design-Team/hive_ce#69]
This should be theoretically possible with an abstraction of the `IsolateNameServer`

**Comment by Rexios80** [comment]
Maybe this is harder than I thought again. Box opening would need to be abstracted out of `HiveImpl` so that it could be isolated

**Comment by felix-ht** [comment]
we are currently using sembast. But looking for a new solution. Sembast also doens't support isolates, which has proven to be a pain for us, as our local dbs tends to be quite large (10k-500k rather large objects). 

If we do a switch, it feels neccersary that it is future proof with regards to isolate support. Drift which is another option does have support for isoaltes.

**Comment by delfme** [comment]
@Rexios80 Yeah, it could be quite complex. Why don't we adopt a solution similar to shardPrefs? It works well, with the only caveat being the need to invoke a `reload()` when the app resumes from the background to ensure the cache is updated with the latest value.

**Comment by delfme** [comment]
If the feature is added we will also migrate to ce, being the only reliable solution for production, and I believe many will do too.

**Comment by delfme** [comment]
Juat noticed this old commit from Simon?https://github.com/isar/hive/commit/1b8f5857ea20bba876d3dc420310f770525d8a86

**Comment by Rexios80** [comment]
> Why don't we adopt a solution similar to shardPrefs?

The backend of shared preferences is meant to handle simultaneous read/write. The issue with Hive is that if you attempt to access it from multiple isolates the database could corrupt.

> Juat noticed this old commit from Simon?

That commit introduces the Isar backend, which is definitely not a valid solution for Hive CE.

I believe the best solution is for Hive to maintain its own isolate for database operations.

**Comment by delfme** [comment]
Hi @Rexios80 wouldnt isolate ports communication impact performance? 
https://github.com/danger-ahead/flutter_isolates_example

https://medium.com/@danger-ahead/working-with-isolates-and-hive-in-flutter-b5ef3d32fa2a

We also noticed that boxes can become corrupted even during read operations in the background. Not sure why.

We were considering using mutex to protect the boxes but ultimately concluded that Hive should only be used when the app is in the foreground and from the main thread. If any properties is required from a background task, it can be read/saved from/to SharedPrefs (we, for example, need to access a few cached properties when performing a background cloud backup). But we keep using hive for all the rest, because we don't like the alternatives, nor we think there are real alternatives. 

For those who might be interested in our setup, we use:
- sqlite db (database, this is the data that we backup)
- hive (key/value cache with some boxes that can have from tens to hundreds entries)
- sharedPrefs (key/value cache to store data that is accessed also from background tasks)
- isar (db for cached data that is accessed via query, from tens to hundreds entries).
Ofc, a simple app can just make it with 2-3 options, but for us Hive is a must-have.

**Comment by Rexios80** [comment]
> wouldnt isolate ports communication impact performance?

Using isolates would be optional

**Comment by Rexios80** [comment]
Good news everyone! I think I got Hive to work across multiple isolates!

The code still needs heavy auditing, but this test file appears to prove that `IsolatedHive` is behaving as expected: https://github.com/IO-Design-Team/hive_ce/blob/a989ed432c70ba094b96123e450f1c170253b14d/hive/test/tests/isolate_test.dart

I need to publish `isolate_channel` before this code is runnable by others, but that's a task for another day.

**Comment by sunderee** [comment]
That would be an amazing feature. Awesome!

**Comment by delfme** [comment]
Wow!! 👏 Will check this asap. How about performance? How this is intended to be used to avoid performance issue?

**Comment by Rexios80** [comment]
@delfme Here's a benchmark

<img width="665" alt="Image" src="https://github.com/user-attachments/assets/58ecde4b-e98e-4bca-91b2-d5402761c1f5" />

Using isolates does seem to introduce measurable overhead, but it isn't much compared to how slow Hive v4 can be

**Comment by Rexios80** [comment]
More good news! IsolatedHive passes all the tests I've thrown at it! There's still work to be done, but if you want to try it out now you can use these dependency overrides:

```yaml
dependency_overrides:
  hive_ce:
    git:
      url: https://github.com/IO-Design-Team/hive_ce
      ref: 30b6dd3a96389d98e1a4167cd9aaa3ca11458172
      path: hive
  hive_ce_flutter:
    git:
      url: https://github.com/IO-Design-Team/hive_ce
      ref: 30b6dd3a96389d98e1a4167cd9aaa3ca11458172
      path: hive_flutter
  hive_ce_generator:
    git:
      url: https://github.com/IO-Design-Team/hive_ce
      ref: 30b6dd3a96389d98e1a4167cd9aaa3ca11458172
      path: hive_generator
```

And then replace `Hive` with `IsolatedHive` everywhere. This will NOT work on web yet because I need to write a wrapper to delegate `IsolatedHive` operations to normal `Hive` on web since web does not support isolates.

**Comment by Rexios80** [comment]
https://github.com/user-attachments/assets/a6599db4-15ce-4f5f-8ca4-2f1edb41f137

Here's a quick and dirty demo of Hive working across multiple isolates in a Flutter app. Although in making this, I learned I have more work left than I thought.

**Comment by Rexios80** [comment]
Quick update:
- `IsolatedHive` should work on web now (although it's just a wrapper for normal `Hive`)
- I resolved the isolate communication issues I alluded to in my previous comment, but the data that is stored from `IsolatedHive` is not compatible with normal `Hive`. This should be fixable, but I just haven't gotten around to it yet.

**Comment by Rexios80** [comment]
Good news again! I think `IsolatedHive` is almost done!

What's left:
- [ ] Add more tests for behavior I had to add to the base `Hive` implementation to support `IsolatedHive`
- [ ] Thoroughly audit the code to make sure the API surface matches the intent
- [ ] Update documentation
- [ ] Create a pre-release on pub.dev so that others can easily test it. I want to make absolutely sure we won't need any breaking changes before I make a stable release.

Here's a link the the quick and dirty demo if you want to see it in action:
https://github.com/Rexios80/flutter_multiwindow/blob/master/lib/main.dart

If you want to try out `IsolatedHive` now:
```yaml
dependency_overrides:
  hive_ce:
    git:
      url: https://github.com/IO-Design-Team/hive_ce
      ref: cf372903350fe10e99480c9232f2a0805d96dd9c
      path: hive
  hive_ce_flutter:
    git:
      url: https://github.com/IO-Design-Team/hive_ce
      ref: cf372903350fe10e99480c9232f2a0805d96dd9c
      path: hive_flutter
  hive_ce_generator:
    git:
      url: https://github.com/IO-Design-Team/hive_ce
      ref: cf372903350fe10e99480c9232f2a0805d96dd9c
      path: hive_generator
```
