### ISSUE TITLE
Opening Multiple app windows

### ISSUE THREAD

**Issue by smwash** [IO-Design-Team/hive_ce#84]
**Question**
Thanks for the efforts towards the package.
How can i have two multiple windows of the same app in windows/macos? 
Trying to open the second window throws this error in debug mode but in release mode a blank screen:
```
     Unhandled Exception: FileSystemException: lock failed, path = 'a path pointing to a lock file' (OS Error: Resource temporarily unavailable, errno = 35)
```
After restarting am getting a debugprint of ''Recovering corrupted box.''
Am also using generate adapters

**Code sample**
```
///Main file
  await Hive.initFlutter();
  Hive.registerAdapters();
  await openHiveBoxes();

///OpenHive boxes file
Future<void> openHiveBoxes() async => await Future.wait([
      Hive.openBox<StockRequisitionItemsParams>(HiveBoxKey.stockRequisitionItem),
      Hive.openBox<BillItemParam>(HiveBoxKey.billItem)
    ]);

```

**Version**
 - Platform: iOS, Android, Mac, Windows, Linux, Web
 - Flutter version: [3.22.2]
 - Hive version: [2.10.1]

**Comment by Rexios80** [comment]
This should be fixable using `IsolatedHive`, but that feature isn't quite ready for release yet. I have no idea if this will actually work, but try this:

```yaml
dependency_overrides:
  hive_ce:
    git:
      url: https://github.com/IO-Design-Team/hive_ce
      ref: 30b6dd3a96389d98e1a4167cd9aaa3ca11458172
      path: hive
  hive_ce_flutter:
    git:
      url: https://github.com/IO-Design-Team/hive_ce
      ref: 30b6dd3a96389d98e1a4167cd9aaa3ca11458172
      path: hive_flutter
  hive_ce_generator:
    git:
      url: https://github.com/IO-Design-Team/hive_ce
      ref: 30b6dd3a96389d98e1a4167cd9aaa3ca11458172
      path: hive_generator
```

Run the code generator, then replace `Hive` with `IsolatedHive` everywhere. Some methods on `IsolatedHive` are asynchronous as opposed to their `Hive` counterparts, so you might have to fix some things. Also `IsolatedHive` doesn't work on web yet. I need to make a wrapper to delegate `IsolatedHive` operations on web to normal `Hive` since web doesn't support isolates.
