### ISSUE TITLE
Generate typeId without `int`

### ISSUE THREAD

**Issue by kealist** [IO-Design-Team/hive_ce#91]
**Is your feature request related to a problem? Please describe.**

<img width="371" alt="Image" src="https://github.com/user-attachments/assets/a092fe96-0056-4b9b-b8e3-6924c10dafc0" />

Is it possible for the generator to generate the TypeAdapter's `typeId` field without `int` for linting purposes?  Not sure how general this lint rule typically is used though.

<img width="698" alt="Image" src="https://github.com/user-attachments/assets/951f954b-90e4-47ae-bfec-4cfff175673a" />

**Comment by Rexios80** [comment]
You can deal with lint issues in generated files by creating a `build.yaml` file with the following contents:

```yaml
targets:
  $default:
    builders:
      source_gen|combining_builder:
        options:
          ignore_for_file:
            - {lint rule 1}
            - {lint rule 2}
```

Updating code generators to satisfy one rule will cause issues if developers have the counterpart rule enforced

By the way I know you know this, but for anyone else reading this DO NOT add generated files to the analysis exclusions. It will only cause more issues.
